version: "3.8"  # Update to the current version

services:
  frontend:
    build:
      context: ./searchvisuals_frontend  # Correct path to your frontend directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Adjust port according to your frontend app
    volumes:
      - ./searchvisuals_frontend:/app
       /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - searchvisuals.backend


  backend:
    build:
      context: ./searchvisual_backend  # Correct path to your backend directory
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Adjust port according to your backend app
    volumes:
      - ./searchvisual_backend:/app
       /app/node_modules
    environment:
      - NODE_ENV=development
